# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# RTD version is required
version: 2
  #
# This can be removed once Python 3.9 is generally available in RTD
build:
  image: testing

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

python:
   version: "3.9"
   install:
     - method: pip
       path: .
       extra_requirements:
         - docs
