name: CI

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install Package
        run:
          pip install -e .[lint]
      - name: Run flake8
        run:
          flake8 remarker tests
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install Package
      run:
        pip install -e .[typecheck]
    - name: Run mypy
      run:
        mypy remarker tests
  test:
    name: Test All
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install Package
        run:
          pip install -e .[tests]
      - name: Run pytest and Generate Coverage Report
        run:
          pytest --cov-report=xml
