name: CI

on:
  # When pushing to any branch, or when creating a new tag, e.g. to make a release.
  push:
    branches: '**'
    tags: 'v*'
  create:
    tags: 'v*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install Package
        run:
          pip install -e .[lint]
      - name: Run flake8
        run:
          python -m flake8 premark tests
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install Package
      run:
        pip install -e .[typecheck]
    - name: Run mypy
      run:
        python -m mypy premark
  test:
    name: Test All
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install Package
        run:
          pip install -e .[test]
      - name: Run pytest and Generate Coverage Report
        run:
          pytest --cov-report=xml
