name: Publish Distributions to PyPI, Test and Prod

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    tags:
      - 'v*'

jobs:
  check-branch:
    # Taken from https://github.community/t/how-to-create-filter-on-both-tag-and-branch/16936/6
    name: Check if tag on main branch
    outputs:
      on_main: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@v1
        id: contains_tag
        with:
          reference: "main"
          tag: "${{ github.ref }}"
  build-n-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install Build and Deploy Tools
        run:
          pip install build twine
      - name: Build wheel and sdist
        run:
          python -m build
      - name: Publish Distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          # In Test PyPI, we don't care about duplicate releases.
          skip_existing: true
      - name: Debug
        run: |
          echo "Are we on main?"
          echo ${{ needs.check-branch.outputs.on_main == 'true' }}
      - name: Publish Distribution to PyPI
        # Only publish to *real* PyPI if this commit has a tag.
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: nonsense to fail #${{ secrets.PYPI_API_TOKEN }}
